### ISSUE TITLE
Content List widget doesn't render related media

### ISSUE THREAD

**Issue by mastercodingbear** [Sitefinity/nextjs-samples#1]
Content List widget doesn't render related media - image of Contents.

**Comment by mstratiev** [comment]
Thank you for your feedback. Additional fields, especially related items fields, for content items will not be displayed OOB in the detail templates. Modifying the widget templates is the suggested approach to customizing the render of the detail items. Public reference for the widget code could be found in the [SDK reference repository](https://github.com/Sitefinity/nextjs-sdk) and used as a base for creating custom widget templates.

Furthermore, Issues for this repository will be disabled shortly. The NextJS external renderer for Sitefinity is still in beta and there is no official dedicated support for it yet.
